collections:
  tools:
    output: true
    permalink: /tools/:name
  articles:
    output: true
    permalink: /articles/:name

url: https://atrxdev.github.io
baseurl: ""

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"